### ISSUE TITLE
Auto-redirect to WWW subdomain

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/BRC#1]
www.brc.ac.uk, but entering brc.ac.uk gives Gateway Timeout: can't connect to remote host. It should support both cases.

Possibly linked to BiologicalRecordsCentre/irecord#53

**Comment by BirenRathod** [comment]
Due to BRC site host somewhere else the reverse proxy doesn't work.

**Comment by BirenRathod** [comment]
This resolved while ago after we moved to new server.

**Comment by kazlauskis** [comment]
Feel free to close this if you think it is no longer an issue.

**Comment by BirenRathod** [comment]
@kazlauskis , I can't as I don't have permissions.
