### ISSUE TITLE
Recording page (https://test-brc-site.pantheonsite.io/recording)

### ISSUE THREAD

**Issue by Kattur** [BiologicalRecordsCentre/BRC#10]
This page looks really smart, I like it a lot.

I think one of the links might be broken though (the 'history of recording').

Also, some of the information in the first paragraph is repeated in the 'what we do' section.

**Comment by BirenRathod** [comment]
@Kattur 'history of recoding' link has been implemented now.  
Information in 'what we do' has amended too.

**Comment by BirenRathod** [comment]
@Kattur please close the issue if it has resolved
