### ISSUE TITLE
The website encounter problem message after saving record.

### ISSUE THREAD

**Issue by BirenRathod** [BiologicalRecordsCentre/BRC#12]
@johnvanbreda 

On this https://www.brc.ac.uk/mammals page, After updating iForm module to 8.10, I got below error. Any idea?
Error: Call to private method data_entry_helper::getSuccessMessage() from context '' in iform_handle_posted_form() (line 690 of /code/web/modules/custom/iform/iform.module)

This happens after submitting record on indicia form.

**Comment by johnvanbreda** [comment]
Have you got both the iform module and the client_helpers sub-module at the head of the master branch? If so, data_entry_helper::getSuccessMessage should be a public method.

**Comment by BirenRathod** [comment]
@johnvanbreda Yes, I have. When I pulled the repository both media and client_helpper modules updated.

**Comment by johnvanbreda** [comment]
Check the code then as that doesn't sound correct.

**Comment by BirenRathod** [comment]
@johnvanbreda data_entry_helper code hasn't updated since March 2022. So that is not right. I have pulled the repository again and updated code now. Thanks. all done.
