### ISSUE TITLE
Add record id field to recording schemes download

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRC#3]
I'm using the list of recording schemes on the BRC website as our master copy of all scheme contact details. I can download the list of schemes as a csv, but it would be useful if that csv included a unique ID for each scheme listed, so that links can be maintained when scheme names change etc.

**Comment by BirenRathod** [comment]
@kitenetter Is it still a requirement?

**Comment by kitenetter** [comment]
@BirenRathod it would still be useful. Not sure it is a priority if it is complex to achieve, but if it can be done easily that would be great.

**Comment by BirenRathod** [comment]
@kitenetter You mentioned above you have managed to download csv, I can't find download link or csv attachment to recording scheme page. Can you send me the link and I will see what I can do best?

**Comment by kitenetter** [comment]
@BirenRathod I think it was Bjorn who passed this on to me:

> Log on to the main BRC website. Go to:
> http://www.brc.ac.uk/schemes-list
> 
> To download all the addresses, select “Any” from the drop-down list at the top and click on “Apply”, then scroll down all the way to the bottom and click on the orange “csv” button. This will produce a csv file containing all the scheme contact details.

**Comment by BirenRathod** [comment]
Thanks, @kitenetter.
I have added the id of scheme, so you could see that in download report too. This is at present only available on test site.
