### ISSUE TITLE
Test website: video link not displaying

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRC#4]
At the foot of this page:
https://test-brc-site.pantheonsite.io/getting-started-biological-recording

there is a YouTube link that is not displaying.

**Comment by BirenRathod** [comment]
@kitenetter 
This has resolved now. 
It has come to my attention while I was checking the issue but I didn't get notification of issue as you didn't assign to me. please do so in other issues.

**Comment by kitenetter** [comment]
Hi @BirenRathod I'm not able to assign people for issues in this repository. Can you add me to the team?

**Comment by BirenRathod** [comment]
@kazlauskis Could you add core role to this BRC repository please? please check if there are others like that. It should not be prevented by BRC members. 
At present I can't assign or anybody to add to assign to me.

**Comment by kazlauskis** [comment]
@BirenRathod it might be better to ask other owners (internal to CEH) to grant you extra permissions. https://github.com/orgs/BiologicalRecordsCentre/people?query=role%3Aowner

**Comment by BirenRathod** [comment]
@kazlauskis I thought because you created, it is easy for you to do that. 
@DavidRoy can you give me the permission on this repository as I can't close or assign the issue.

**Comment by DavidRoy** [comment]
@BirenRathod I've set you as admin and added @kitenetter to the team

**Comment by BirenRathod** [comment]
That is fantastic, Many thanks @DavidRoy.

@kitenetter you can now assign other issues same as this one.
