### ISSUE TITLE
Test website: menu structure has obscured key themes

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRC#5]
The list of "Key themes" is prominent on the existing website, but is hidden under a top-level menu on the test site. At least some of the key themes need to be directly available from the home page, e.g. the list of recording schemes.

We probably need to think about the overall menu structure for the site and focus on the most important and relevant items.

**Comment by BirenRathod** [comment]
@kitenetter Yes, we could think about restructuring of menu, so if you have any suggestion would be good. perhaps discussing with @DavidRoy.
