### ISSUE TITLE
Images on the carousel 

### ISSUE THREAD

**Issue by Kattur** [BiologicalRecordsCentre/BRC#6]
Due to the increased size of the carousel, the poor quality of some of the images is now more apparent.

Either the images need to be replaced, or the carousel size reduced.

**Comment by BirenRathod** [comment]
@Kattur 
Reducing carousel size would not be efficient way to display carousel on the page as actual width is bigger than live BRC website page. 
For existing images, you can upload the resize images. By the way new image size is 1140 x 308. We need to implement that size in how to doc.

**Comment by Kattur** [comment]
That's a pity because it is a very large carousel and unfortunately shunts the Welcome to the BRC information to the very bottom of the screen (in fact, some of the text doesn't even shown on my screen). However, I understand what you mean in terms of the proportions of the new site.  Also, it maybe that this new layout suits other devices better (I'm not able to check myself as I only have pc/laptop).

If the carousel size cannot me changed, then maybe the carousel style could be changed?- at the moment the text section to the right looks a bit odd to me.... but I realise others may disagree, so please don't make any changes to it unless anyone else also thinks it is worth changing.

**Comment by BirenRathod** [comment]
@Kattur It is bit complicate to adjust screen on laptop as laptop screen is shorter from height. Width is not a problem, it is just the height.
If you have any example site I could think of arranging that way (not right now) but we can consider as a possible future display. dipterists.org.uk is another example where we use different display.
