### ISSUE TITLE
Carousel image transistion

### ISSUE THREAD

**Issue by Kattur** [BiologicalRecordsCentre/BRC#7]
The sliding between images makes me feel really dizzy very quickly. Can the transition be changed to some other style?

**Comment by BirenRathod** [comment]
@Kattur 
Unfortunately, there is only one transition available but I have increased the interval.

**Comment by BirenRathod** [comment]
@Kattur Although, I mentioned above about the only possible option at present but in future as theme gets future update there will be more options available. So I'm not ruling out for future update.
