### ISSUE TITLE
Carousel navigation buttons

### ISSUE THREAD

**Issue by Kattur** [BiologicalRecordsCentre/BRC#8]
On the live site, there are navigation buttons below the carousel. This allows people some control with the navigation back and forth through the images.

**Comment by BirenRathod** [comment]
@Kattur 
I thought it is trivial but I can reintroduced.

**Comment by BirenRathod** [comment]
@Kattur  I have reintroduced now.

**Comment by Kattur** [comment]
I like the arrows 👍
